DROP TABLE Evaluations;
DROP TABLE Utilisateurs CASCADE CONSTRAINTS;
DROP TABLE Taches CASCADE CONSTRAINTS;
DROP TABLE TachesAtom CASCADE CONSTRAINTS;
DROP TABLE Competences CASCADE CONSTRAINTS;
DROP TABLE Candidatures;
DROP TABLE CompetencesUtilisateurs;
DROP TABLE CompetencesTaches;